from load_data import load_dataframe

COUNTRIES_STOPWORDS = [
    "austria",
    "austrian",
    "belgium",
    "belgian",
    "bulgaria",
    "bulgarian",
    "czech",
    "cyprus",
    "cypriot",
    "germany",
    "german",
    "denmark",
    "danish",
    "estonia",
    "estonian",
    "croatia",
    "croatian",
    "finland",
    "finnish",
    "france",
    "french",
    "malta",
    "maltese",
    "luxembourg",
    "lithuania",
    "lithuanian",
    "latvia",
    "latvian",
    "italy",
    "italian",
    "ireland",
    "irish",
    "hungary",
    "hungarian",
    "greece",
    "greek",
    "spain",
    "spanish",
    "netherlands",
    "dutch",
    "poland",
    "polish",
    "portugal",
    "portuguese",
    "romania",
    "romanian",
    "sweden",
    "swedish",
    "slovenia",
    "slovenian",
    "slovakia",
    "slovak",
]

NECP_STOPWORDS = [
    "energy",
    "figure",
    "table",
    "plan",
    "necp",
    "national",
    "use",
    "measure",
    "sector",
    "climate",
    "plan",
    "dimension",
    "integrated",
    "section",
    "republic",
    "measures",
    "policies",
    "target",
    "objective",
    "policy",
    "projection",
    "assessment",
    "federal",
    "government",
]


STOPWORDS = COUNTRIES_STOPWORDS + NECP_STOPWORDS
PARAGRAPHS = [
    "Overview and Process for Establishing the Plan",
    "Impact Assessment of Planned Policies and Measures",
]
DIMENSIONS = ["Decarbonisation",
    "Energy efficiency",
    "Energy security",
    "Internal market",
    "R&I and Competitiveness",]
COMMON_WORDS = {
    "Overview and Process for Establishing the Plan": ["electricity"],
    "Impact Assessment of Planned Policies and Measures": ["scenario", "increase", "electricity"],
    "Decarbonisation": ["emission", "renewable", "transport", "electricity", "increase"],
    "Energy efficiency": ["efficiency", "building", "consumption"],
    "Energy security": ["gas", "electricity"],
    "Internal market": ["electricity", "market", "gas", "system"],
    "R&I and Competitiveness": ["research", "technology", "innovation"],
}
