from load_data import load_dataframe

COUNTRIES_STOPWORDS = [
    "austria",
    "austrian",
    "belgium",
    "belgian",
    "bulgaria",
    "bulgarian",
    "czech",
    "cyprus",
    "cypriot",
    "germany",
    "german",
    "denmark",
    "danish",
    "estonia",
    "estonian",
    "croatia",
    "croatian",
    "finland",
    "finnish",
    "france",
    "french",
    "malta",
    "maltese",
    "luxembourg",
    "lithuania",
    "lithuanian",
    "latvia",
    "latvian",
    "italy",
    "italian",
    "ireland",
    "irish",
    "hungary",
    "hungarian",
    "greece",
    "greek",
    "spain",
    "spanish",
    "netherlands",
    "dutch",
    "poland",
    "polish",
    "portugal",
    "portuguese",
    "romania",
    "romanian",
    "sweden",
    "swedish",
    "slovenia",
    "slovenian",
    "slovakia",
    "slovak",
]

STOPWORDS = COUNTRIES_STOPWORDS

PARAGRAPHS = [
    "Summary",
    "National schemes",
    "Links with labour market activation",
    "Links to social services",
    "Governance mechanisms",
    "Impact of minimum income schemes",
]

COMMON_WORDS = {
    'Summary': ['social', 'benefit', 'income', 'support', 'scheme'],
    'National schemes': ['benefit', 'income', 'social', 'household', 'child'],
    'Links with labour market activation': ['benefit', 'social', 'recipient', 'work', 'service', 'employment', 'income', 'job', 'beneficiary', 'month'],
    'Links to social services': ['social', 'service', 'social service', 'benefit', 'support', 'recipient', 'provide'],
    'Governance mechanisms': ['social', 'benefit', 'service', 'social assistance', 'income', 'scheme'],
    'Impact of minimum income schemes': ['benefit', 'income', 'social', 'poverty', 'scheme', 'minimum']
}
